{
  "cveMetadata": {
    "state": "PUBLISHED",
    "cveId": "CVE-2025-55553",
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "assignerShortName": "mitre",
    "dateUpdated": "2025-09-29T17:30:11.735Z",
    "dateReserved": "2025-08-13T00:00:00.000Z",
    "datePublished": "2025-09-25T00:00:00.000Z"
  },
  "containers": {
    "cna": {
      "providerMetadata": {
        "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "shortName": "mitre",
        "dateUpdated": "2025-09-25T15:11:38.959Z"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "A syntax error in the component proxy_tensor.py of pytorch v2.7.0 allows attackers to cause a Denial of Service (DoS)."
        }
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "version": "n/a",
              "status": "affected"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/pytorch/pytorch/issues/151432"
        },
        {
          "url": "https://github.com/pytorch/pytorch/pull/154645"
        },
        {
          "url": "https://gist.github.com/shaoyuyoung/0e7d2a586297ae9c8ed14d8706749efc"
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "type": "text",
              "lang": "en",
              "description": "n/a"
            }
          ]
        }
      ]
    },
    "adp": [
      {
        "problemTypes": [
          {
            "descriptions": [
              {
                "type": "CWE",
                "cweId": "CWE-248",
                "lang": "en",
                "description": "CWE-248 Uncaught Exception"
              }
            ]
          }
        ],
        "references": [
          {
            "url": "https://github.com/pytorch/pytorch/issues/151432",
            "tags": [
              "exploit"
            ]
          }
        ],
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 7.5,
              "attackVector": "NETWORK",
              "baseSeverity": "HIGH",
              "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "integrityImpact": "NONE",
              "userInteraction": "NONE",
              "attackComplexity": "LOW",
              "availabilityImpact": "HIGH",
              "privilegesRequired": "NONE",
              "confidentialityImpact": "NONE"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "timestamp": "2025-09-29T17:28:46.243940Z",
                "id": "CVE-2025-55553",
                "options": [
                  {
                    "Exploitation": "poc"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "role": "CISA Coordinator",
                "version": "2.0.3"
              }
            }
          }
        ],
        "title": "CISA ADP Vulnrichment",
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2025-09-29T17:30:11.735Z"
        }
      }
    ]
  },
  "search": "解析验收测试文案"
}