{
  "cveMetadata": {
    "cveId": "CVE-2025-61622",
    "assignerOrgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
    "state": "PUBLISHED",
    "assignerShortName": "apache",
    "dateReserved": "2025-09-29T06:47:23.146Z",
    "datePublished": "2025-10-01T09:55:05.557Z",
    "dateUpdated": "2025-10-01T13:08:39.262Z"
  },
  "containers": {
    "cna": {
      "affected": [
        {
          "collectionURL": "https://pypi.python.org",
          "defaultStatus": "unaffected",
          "packageName": "pyfory",
          "product": "Apache Fory",
          "vendor": "Apache Software Foundation",
          "versions": [
            {
              "lessThanOrEqual": "0.12.2",
              "status": "affected",
              "version": "0.12.0",
              "versionType": "semver"
            }
          ]
        },
        {
          "collectionURL": "https://pypi.python.org",
          "defaultStatus": "unaffected",
          "packageName": "pyfury",
          "product": "Apache Fory",
          "vendor": "Apache Software Foundation",
          "versions": [
            {
              "lessThanOrEqual": "0.10.3",
              "status": "affected",
              "version": "0.1.0",
              "versionType": "semver"
            }
          ]
        }
      ],
      "credits": [
        {
          "lang": "en",
          "type": "reporter",
          "value": "Mapta / BugBunny_ai"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "supportingMedia": [
            {
              "base64": false,
              "type": "text/html",
              "value": "<span style=\"background-color: rgb(255, 255, 255);\">Deserialization of untrusted data in&nbsp;python in <span style=\"background-color: rgb(255, 255, 255);\">pyfory&nbsp;</span>versions 0.12.0 through 0.12.2, or the&nbsp;<span style=\"background-color: rgb(255, 255, 255);\">legacy&nbsp;<span style=\"background-color: rgb(255, 255, 255);\">pyfury versions from</span></span><span style=\"background-color: rgb(255, 255, 255);\">&nbsp;0.1.0 through 0.10.3:</span> allows arbitrary code execution. An application is vulnerable if it reads pyfory serialized data from untrusted sources.&nbsp;<span style=\"background-color: rgb(255, 255, 255);\">An attacker can craft a data stream that selects pickle-fallback serializer during deserialization, leading to the execution of `pickle.loads`, which is&nbsp;vulnerable to&nbsp;<span style=\"background-color: rgb(255, 255, 255);\">remote code execution.<br><br>Users are recommended to upgrade to pyfory version 0.12.3 or later, which has removed pickle fallback serializer and thus fixes this issue.<br></span></span></span><br>"
            }
          ],
          "value": "Deserialization of untrusted data in python in pyfory versions 0.12.0 through 0.12.2, or the legacy pyfury versions from 0.1.0 through 0.10.3: allows arbitrary code execution. An application is vulnerable if it reads pyfory serialized data from untrusted sources. An attacker can craft a data stream that selects pickle-fallback serializer during deserialization, leading to the execution of `pickle.loads`, which is vulnerable to remote code execution.\n\nUsers are recommended to upgrade to pyfory version 0.12.3 or later, which has removed pickle fallback serializer and thus fixes this issue."
        }
      ],
      "metrics": [
        {
          "other": {
            "content": {
              "text": "critical"
            },
            "type": "Textual description of severity"
          }
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "cweId": "CWE-502",
              "description": "CWE-502 Deserialization of Untrusted Data",
              "lang": "en",
              "type": "CWE"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "f0158376-9dc2-43b6-827c-5f631a4d8d09",
        "shortName": "apache",
        "dateUpdated": "2025-10-01T09:55:05.557Z"
      },
      "references": [
        {
          "tags": [
            "vendor-advisory"
          ],
          "url": "https://lists.apache.org/thread/vfn9hp9qt06db5yo1gmj3l114o3o2csd"
        }
      ],
      "source": {
        "discovery": "UNKNOWN"
      },
      "title": "Apache Fory, Apache Fory: Python RCE via unguarded pickle fallback serializer in pyfory"
    },
    "adp": [
      {
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 9.8,
              "attackVector": "NETWORK",
              "baseSeverity": "CRITICAL",
              "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "integrityImpact": "HIGH",
              "userInteraction": "NONE",
              "attackComplexity": "LOW",
              "availabilityImpact": "HIGH",
              "privilegesRequired": "NONE",
              "confidentialityImpact": "HIGH"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "timestamp": "2025-10-01T13:07:55.196758Z",
                "id": "CVE-2025-61622",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "total"
                  }
                ],
                "role": "CISA Coordinator",
                "version": "2.0.3"
              }
            }
          }
        ],
        "title": "CISA ADP Vulnrichment",
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2025-10-01T13:08:39.262Z"
        }
      }
    ]
  },
  "search": "解析验收测试文案"
}